### PR TITLE
ADD EMC2 tutorial notebook and presentation

### PR DESCRIPTION
**Pull request by isilber**

### CODE REVIEW

**Comment by mgrover1** [comment]
@isilber let me know when you want me to take a look! I am willing to provide feedback!

**Comment by isilber** [comment]
@mgrover1 you are welcome to take a look, thanks!
Note that the notebook requires the recent EMC2 commits, pushed after the v. 1.2 release (Bobby will soon make a new release on conda-forge).

**Comment by mgrover1** [comment]
Great work @isilber ! I left a few comments - feel free to take a look/make some changes!

**Review by mgrover1 — CHANGES_REQUESTED** [review]
Looks good overall - just a few changes! Also, you will need to add the path to this content in the table of contents file (`_toc.yml`)

**Comment by isilber** [comment]
Thanks for the feedback, @mgrover1 . I updated the files accordingly.

**Comment by mgrover1** [comment]
@isilber one other small request - can you modify the path to your data file to be in a `/data` directory in the `/tutorials` directory?

**Comment by isilber** [comment]
Done

**Comment by mgrover1** [comment]
@isilber do you mind if I go ahead and merge?

**Pull request merged**
